= Asciidoctor Maven Plugin: AsciiDoc to EPUB Example

An example project that demonstrates how to convert AsciiDoc to EPUB using Asciidoctor EPUB3 with the Asciidoctor Maven plugin
and the Asciidoctor Lifecycle Maven plugin.

== Usage

=== EPUB

Convert the AsciiDoc to EPUB using Asciidoctor EPUB3 by invoking the `process-resources` goal:

 $ mvn build

Open the file _target/generated-docs/spine.epub_ in your epub viewer to see the generated epub.

=== MOBI

If you want to generate a kindle document, you can enable a second execution block in the pom.xml. If _kindlegen_ is in your path (you have to download it for your OS from amazon here: https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211) a mobi file should be generated. Currently however the maven plugin exits with an error ((Errno::ECHILD) No child processes)).

== Differences from the original example

. Construction is executed on `build` phase, not in `process-resources` phase.
. The kindlegen execution was commented because it is not relevant for this example.
. The example project packaging is `pom`, instead of `jar`, to avoid generating an empty jar.
. Please, note that if you invoke the `package` goal you don't get nothing.
This is the expected result, because we are using the lifecycle.