= Asciidoctor Maven Plugin: AsciiDoc to PDF Book Example

An example project that demonstrates how to convert AsciiDoc to PDF using Asciidoctor PDF with the Asciidoctor Maven plugin
and the Asciidoctor Lifecycle Maven plugin.

This example produces a book and make use of a YAML style sheet (defined in the theme artifact).
The same document is rendered twice:

* Without the theme configuration, output is `target/generated-docs-default-theme/example-manual.pdf`
* With the theme configuration, output is `target/generated-docs-custom-theme/example-manual.pdf`

== Usage

=== Requirement

This example tries to download the theme artifact `com.coutemeier.maven.plugins:asciidoctor-create-theme-example:zip:1.0.0-SNAPSHOT`.
The sources for this theme are in `asciidoctor-create-theme-example` module.

If you don't do before, you must manually build the `asciidoctor-create-theme-example` module using:

[source,shell]
mvn install

After that the theme will be installed in your local repository and you will be able to build this example.

=== Build the example

Convert the AsciiDoc to PDF using Asciidoctor PDF by invoking the `build` goal:

 $ mvn build

Open the file _target/generated-docs-custom-theme/example-manual.pdf_ in your PDF viewer to see the generated PDF.

== Differences from the original example

. `process-asciidoc` is executed on `build` phase, not in `process-resources` phase.
. The example project packaging is `pom`, instead of `jar`, to avoid generating an empty jar.
. Uses the theme `com.coutemeier.maven.plugins:asciidoctor-create-theme-example:zip:1.0.0-SNAPSHOT` created before.
. The theme is defined in the `asciidoctor-lifecycle-maven-plugin` configuration. This theme can be reused in multiple projects.
It is downloaded and unzipped at `${project.build.directory}/asciidoctor-themes/asciidoctor-create-theme-example`.
The property `mytheme.pdf.path` is created to reflect its path.
. The `src/theme` directory has been removed, because it is not needed anymore.
. Please, note that if you invoke the `package` goal you don't get nothing.
This is the expected result, because we are using the lifecycle.